### ISSUE TITLE
cpu support

### ISSUE THREAD

**Issue by cycyyy** [numap-library/numap#5]
I'm not familiar with cpu PMU so that could you please add the support to this cpu arch? here is cpu information:
Architecture:          x86_64
Byte Order:            Little Endian
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 87
Model name:            Intel(R) Xeon Phi(TM) CPU 7210 @ 1.30GHz

The intel doc mention it in 18.14 (https://www.intel.com/content/www/us/en/architecture-and-technology/64-ia-32-architectures-software-developer-system-programming-manual-325384.html) 
 And here is another doc: https://software.intel.com/en-us/articles/intel-xeon-phi-x200-family-processor-performance-monitoring-reference-manual
Based on TABLE 2-4 in https://software.intel.com/sites/default/files/managed/6e/3d/Intel%C2%AE%20Xeon%20Phi%E2%84%A2%20Processor%20Performance%20Monitoring%20Reference%20Manual_Vol2_Mar2017.pdf i think it's MEM_UOPS_RETIRED:ALL_LOADS and MEM_UOPS_RETIRED:ALL_STORES
Thank you very much!

**Comment by cycyyy** [comment]
“MEM_UOPS_RETIRED
• Event Select: 4h
• Event Description: Counts the number of memory micro-ops retired. Prefetches
will not be counted.”
I read this event in the [doc](https://software.intel.com/sites/default/files/managed/6e/3d/Intel%C2%AE%20Xeon%20Phi%E2%84%A2%20Processor%20Performance%20Monitoring%20Reference%20Manual_Vol2_Mar2017.pdf). Does it work for numap?

**Comment by trahay** [comment]
I pushed a new branch (xeon_phi) that adds these events for xeon phi. I could not test it, so please let me know if it works for you.

**Comment by ManuelSelva** [comment]
> I pushed a new branch (xeon_phi) that adds these events for xeon phi. I could not test it, so please let me know if it works for you.

François, does this event supports PEBS ?

**Comment by trahay** [comment]
@ManuelSelva I'm not sure (that's why i pushed it on a new branch). On some architectures, there are some "mem_trans_retired;all_stores events" in PEBS, so these events may be from PEBS

**Comment by ManuelSelva** [comment]
@trahay Ok I understand now. Thank you very much for the support and let's wait for @cycyyy try on the actual machine to see if it works.

**Comment by cycyyy** [comment]
I tested on my server and it's cause the "Segmentation fault".
I also asked the professor and he said that xeon_phi hasn't supported for PEBS now so that it couldn't be used for detailed samples. Thank you for your support @trahay @ManuelSelva 
But i still can't figure out the difference between "MEM_TRANS_RETIRED" and "MEM_UOPS_RETIRED". What's more , the doc didn't mention whether the CPU support PEBS or not...
